Repository AY2425S1-CS2103T-F09-4/tp, pull requests merged in 2024-11, with the labels that each got.

#171 Bug Fix: Fail test case because lessons overflow to next day
  src/test/java/tuteez/model/person/PersonTest.java
Labels: type.Bug, severity.Low

#177 Change tags to allow spaces
  src/main/java/tuteez/model/tag/Tag.java
  src/test/java/tuteez/model/tag/TagTest.java
Labels: type.Enhancement, priority.Low, severity.Low

#186 Add comments
  src/test/java/tuteez/model/person/lesson/DayTest.java
Labels: type.Task, priority.Medium

#185 Remove display after clear is executed
  src/main/java/tuteez/logic/commands/ClearCommand.java
  src/test/java/tuteez/logic/commands/ClearCommandTest.java
Labels: type.Bug, priority.High, severity.Low, alpha-bug

#184 Update test cases with equivalence partitioning and boundary values
  src/test/java/tuteez/logic/commands/AddCommandTest.java
  src/test/java/tuteez/model/person/lesson/LessonTest.java
Labels: type.Task, priority.Medium

#175 Branch update javadocs to list
  src/main/java/tuteez/logic/commands/EditCommand.java
  src/main/java/tuteez/model/person/Person.java
  src/main/java/tuteez/model/person/lesson/Lesson.java
  src/main/java/tuteez/model/person/lesson/LessonManager.java
  src/main/java/tuteez/model/util/SampleDataUtil.java
Labels: priority.High, type.Documentation

#165 Better abstraction for dynamically displaying student details
  src/main/java/tuteez/logic/commands/DeleteCommand.java
  src/main/java/tuteez/logic/commands/EditCommand.java
  src/main/java/tuteez/model/Model.java
  src/main/java/tuteez/model/ModelManager.java
  src/test/java/tuteez/logic/commands/AddCommandTest.java
  src/test/java/tuteez/logic/commands/EditCommandTest.java
  src/test/java/tuteez/model/ModelManagerTest.java
Labels: type.Enhancement, priority.Medium, severity.VeryLow

#187 Change display message
  src/main/java/tuteez/logic/Messages.java
  src/main/java/tuteez/logic/commands/DisplayCommand.java
  src/test/java/tuteez/logic/commands/DisplayCommandTest.java
Labels: priority.Low, severity.VeryLow

#169 Refactor: Abstract portions of `AddCommand#execute`
  src/main/java/tuteez/logic/commands/AddCommand.java
  src/main/java/tuteez/model/AddressBook.java
  src/main/java/tuteez/model/person/Person.java
  src/main/java/tuteez/model/person/lesson/Lesson.java
  src/main/java/tuteez/model/person/lesson/LessonManager.java
  src/test/java/tuteez/logic/commands/AddCommandTest.java
Labels: type.Task

#138 Create a new Lesson Command
  src/main/java/tuteez/logic/Messages.java
  src/main/java/tuteez/logic/commands/AddCommand.java
  src/main/java/tuteez/logic/commands/AddLessonCommand.java
  src/main/java/tuteez/logic/commands/DeleteLessonCommand.java
  src/main/java/tuteez/logic/commands/EditCommand.java
  src/main/java/tuteez/logic/commands/LessonCommand.java
  src/main/java/tuteez/logic/parser/AddLessonCommandParser.java
  src/main/java/tuteez/logic/parser/AddressBookParser.java
  src/main/java/tuteez/logic/parser/CliSyntax.java
  src/main/java/tuteez/logic/parser/DeleteLessonCommandParser.java
  src/main/java/tuteez/logic/parser/ParserUtil.java
  src/main/java/tuteez/model/person/TelegramUsername.java
  src/test/java/tuteez/logic/commands/AddLessonCommandTest.java
  src/test/java/tuteez/logic/commands/CommandTestUtil.java
  src/test/java/tuteez/logic/commands/DeleteLessonCommandTest.java
  src/test/java/tuteez/logic/commands/LessonCommandTest.java
  src/test/java/tuteez/logic/parser/AddLessonCommandParserTest.java
  src/test/java/tuteez/logic/parser/DeleteLessonCommandParserTest.java
  src/test/java/tuteez/testutil/TypicalIndexes.java
Labels: type.Enhancement, priority.Medium

#172 Update Display Panel
  src/main/java/tuteez/ui/DisplayCard.java
  src/main/java/tuteez/ui/DisplayCardPanel.java
  src/main/java/tuteez/ui/MainWindow.java
  src/main/java/tuteez/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DisplayCard.fxml
  src/main/resources/view/DisplayCardPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: priority.High, severity.High, type.Ui

#195 Add logging and assertion statements for improved debugging
  src/main/java/tuteez/logic/commands/AddCommand.java
  src/main/java/tuteez/model/ModelManager.java
  src/main/java/tuteez/model/person/lesson/Lesson.java
Labels: type.Task, severity.Low

#201 Update UG for find command
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#153 Expand use of find command
  src/main/java/tuteez/logic/Messages.java
  src/main/java/tuteez/logic/commands/FindCommand.java
  src/main/java/tuteez/logic/parser/ArgumentTokenizer.java
  src/main/java/tuteez/logic/parser/FindCommandParser.java
  src/main/java/tuteez/model/person/lesson/Lesson.java
  src/main/java/tuteez/model/person/predicates/AddressContainsKeywordsPredicate.java
  src/main/java/tuteez/model/person/predicates/CombinedPredicate.java
  src/main/java/tuteez/model/person/predicates/LessonContainsKeywordsPredicate.java
  src/main/java/tuteez/model/person/predicates/NameContainsKeywordsPredicate.java
  src/main/java/tuteez/model/person/predicates/TagContainsKeywordsPredicate.java
  src/main/java/tuteez/model/tag/Tag.java
  src/test/java/tuteez/logic/commands/CommandTestUtil.java
  src/test/java/tuteez/logic/commands/FindCommandTest.java
  src/test/java/tuteez/logic/parser/AddressBookParserTest.java
  src/test/java/tuteez/logic/parser/FindCommandParserTest.java
  src/test/java/tuteez/model/ModelManagerTest.java
  src/test/java/tuteez/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/tuteez/model/person/predicates/AddressContainsKeywordsPredicateTest.java
  src/test/java/tuteez/model/person/predicates/CombinedPredicateTest.java
  src/test/java/tuteez/model/person/predicates/LessonContainsKeywordsPredicateTest.java
  src/test/java/tuteez/model/person/predicates/TagContainsKeywordsPredicateTest.java
  src/test/java/tuteez/testutil/PersonUtil.java
Labels: type.Story, priority.High

#202 Refactor UI utility methods into a centralized UiUtil class
  src/main/java/tuteez/commons/util/UiUtil.java
  src/main/java/tuteez/ui/DisplayCard.java
  src/main/java/tuteez/ui/PersonCard.java
Labels: priority.Medium, severity.Low, type.Ui

#190 docs: Update User Guide with Lesson Constraints and table of contents
  docs/UserGuide.md
  docs/images/Ui.png
Labels: priority.High, type.Documentation

#189 Branch improve `Lesson` error messages
  src/main/java/tuteez/logic/parser/ParserUtil.java
  src/main/java/tuteez/model/person/lesson/Lesson.java
  src/main/java/tuteez/model/person/predicates/LessonContainsKeywordsPredicate.java
  src/test/java/tuteez/logic/parser/ParserUtilTest.java
  src/test/java/tuteez/model/person/lesson/LessonTest.java
Labels: type.Enhancement, severity.Medium

#197 Remove the ability to add/edit/remove `Lesson`s via `EditCommand`
  src/main/java/tuteez/logic/commands/EditCommand.java
  src/main/java/tuteez/logic/parser/EditCommandParser.java
  src/test/java/tuteez/logic/commands/CommandTestUtil.java
  src/test/java/tuteez/logic/commands/EditCommandTest.java
  src/test/java/tuteez/logic/commands/EditPersonDescriptorTest.java
  src/test/java/tuteez/logic/parser/EditCommandParserTest.java
  src/test/java/tuteez/testutil/EditPersonDescriptorBuilder.java
  src/test/java/tuteez/testutil/PersonBuilder.java
Labels: priority.Medium

#210 Add `addlesson` and `deletelesson` documentation to UG
  docs/UserGuide.md
Labels: type.Documentation

#204 Add labels to person card
  src/main/java/tuteez/ui/DisplayCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
Labels: priority.Medium, severity.Medium, type.Ui

#213 Update display after lesson changes
  src/main/java/tuteez/logic/commands/AddLessonCommand.java
  src/main/java/tuteez/logic/commands/AddRemarkCommand.java
  src/main/java/tuteez/logic/commands/DeleteLessonCommand.java
  src/main/java/tuteez/logic/commands/DeleteRemarkCommand.java
Labels: type.Task, severity.High

#215 Update DG for up and down arrow keys
  docs/DeveloperGuide.md
  docs/diagrams/CommandBoxSequenceDiagram.puml
  docs/diagrams/CommandBoxSequenceDiagram2.puml
Labels: type.Documentation

#220 Standardise message outputs to use student
  src/main/java/tuteez/logic/Messages.java
  src/main/java/tuteez/logic/commands/AddCommand.java
  src/main/java/tuteez/logic/commands/AddRemarkCommand.java
  src/main/java/tuteez/logic/commands/DeleteCommand.java
  src/main/java/tuteez/logic/commands/DeleteRemarkCommand.java
  src/main/java/tuteez/logic/commands/DisplayCommand.java
  src/main/java/tuteez/logic/commands/EditCommand.java
  src/main/java/tuteez/logic/commands/ListCommand.java
  src/test/java/tuteez/logic/commands/AddCommandIntegrationTest.java
  src/test/java/tuteez/logic/commands/AddCommandTest.java
  src/test/java/tuteez/logic/commands/DeleteRemarkCommandTest.java
  src/test/java/tuteez/logic/commands/EditCommandTest.java
Labels: type.Bug, priority.Medium, severity.VeryLow

#191 Fix bugs for `LessonCommand` structure and update test cases
  src/main/java/tuteez/logic/commands/AddLessonCommand.java
  src/main/java/tuteez/logic/commands/DeleteLessonCommand.java
  src/main/java/tuteez/logic/commands/LessonCommand.java
  src/main/java/tuteez/logic/parser/DeleteLessonCommandParser.java
  src/test/java/tuteez/logic/commands/AddLessonCommandTest.java
  src/test/java/tuteez/logic/commands/CommandTestUtil.java
  src/test/java/tuteez/logic/commands/DeleteLessonCommandTest.java
  src/test/java/tuteez/logic/commands/LessonCommandTest.java
  src/test/java/tuteez/logic/parser/AddLessonCommandParserTest.java
  src/test/java/tuteez/logic/parser/AddressBookParserTest.java
  src/test/java/tuteez/logic/parser/DeleteLessonCommandParserTest.java
Labels: type.Bug

#226 Fix bug pertaining to Tip in the UG
  docs/UserGuide.md
Labels: type.Documentation

#228 Edit remark message
  src/main/java/tuteez/logic/commands/AddLessonCommand.java
  src/main/java/tuteez/logic/commands/AddRemarkCommand.java
  src/main/java/tuteez/model/remark/Remark.java
Labels: type.Task, severity.VeryLow

#229 Refactor split pane divider
  src/main/java/tuteez/ui/MainWindow.java
Labels: type.Bug, priority.High, severity.VeryLow

#234 Make index error more specific
  src/main/java/tuteez/logic/Messages.java
  src/main/java/tuteez/logic/commands/AddCommand.java
  src/main/java/tuteez/logic/commands/EditCommand.java
  src/main/java/tuteez/logic/parser/AddLessonCommandParser.java
  src/main/java/tuteez/logic/parser/AddRemarkCommandParser.java
  src/main/java/tuteez/logic/parser/DeleteLessonCommandParser.java
  src/main/java/tuteez/logic/parser/DeleteRemarkCommandParser.java
  src/main/java/tuteez/logic/parser/EditCommandParser.java
  src/test/java/tuteez/logic/parser/AddLessonCommandParserTest.java
  src/test/java/tuteez/logic/parser/AddRemarkCommandParserTest.java
  src/test/java/tuteez/logic/parser/DeleteLessonCommandParserTest.java
  src/test/java/tuteez/logic/parser/DeleteRemarkCommandParserTest.java
  src/test/java/tuteez/logic/parser/EditCommandParserTest.java
Labels: type.Bug, priority.High, severity.Low

#233 Refactor DeleteLessonCommand to sort lessons before deleting
  docs/UserGuide.md
  src/main/java/tuteez/logic/commands/AddLessonCommand.java
  src/main/java/tuteez/logic/commands/DeleteLessonCommand.java
  src/test/java/tuteez/logic/commands/AddLessonCommandTest.java
  src/test/java/tuteez/logic/commands/DeleteLessonCommandTest.java
Labels: type.Bug

#239 Update UG and DG for display
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: severity.VeryLow, type.Documentation

#238 Update version in MainApp
  src/main/java/tuteez/MainApp.java
Labels: priority.Low, severity.Low

#243 Update user guide with tutorial section
  docs/UserGuide.md
  docs/images/add_command_tutorial.png
  docs/images/addlesson_command_tutorial.png
  docs/images/clear_command_tutorial.png
  docs/images/delete_command_tutorial.png
  docs/images/edit_command_tutorial.png
Labels: type.Documentation

#328 Fix formatting issues of UG
  docs/UserGuide.md
  docs/images/annotated_ui.png
Labels: priority.High, type.Documentation

#330 Fix whitespace and newline issues in UG
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#340 Fix formatting and whitespace issues in UG
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#333 Correct delete error message for incorrect format
  src/main/java/tuteez/logic/parser/DeleteCommandParser.java
  src/test/java/tuteez/logic/parser/DeleteCommandParserTest.java
Labels: type.Bug, priority.High, severity.Low

#348 Format and add relevant details to UG
  docs/UserGuide.md
  docs/images/TUTEEZ.png
  docs/images/tuteez_logo.png
Labels: priority.High, type.Documentation

#336 Fix Some DG Bugs in PE-D
  docs/DeveloperGuide.md
  docs/diagrams/DisplaySequenceDiagram.puml
Labels: type.Documentation

#349 docs: Update TOC, add FAQ and future feature
  docs/UserGuide.md
  docs/images/tuteez_logo.png
Labels: type.Documentation

#356 Update heading links
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#344 Fix bug where the next lesson only updates for student in view
  src/main/java/tuteez/ui/PersonListPanel.java
Labels: type.Bug, priority.Medium, severity.Medium

#359 Edit DG ToC and fix miscellaneous issues
  docs/DeveloperGuide.md
Labels: priority.High, type.Documentation

#367 Change UG Product release number
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#366 Fix display sequence diagram
  docs/DeveloperGuide.md
  docs/diagrams/DisplaySequenceDiagram.puml
Labels: priority.High, type.Documentation

#369 Update product website
  docs/index.md
Labels: priority.High

#372 Add missing detail for sequence diagrams
  docs/diagrams/DisplaySequenceDiagram.puml
  docs/diagrams/FindSequenceDiagram.puml
Labels: priority.High, type.Documentation
