Repository AY2425S1-CS2103T-F09-4/tp, pull requests merged in 2024-10, with the labels that each got.

#54 Update CSS colors to match Figma wireframe
  src/main/resources/view/DarkTheme.css
Labels: priority.High

#57 Update `DeleteCommand` to accept the `Name` of a `Person`
  src/main/java/tuteez/logic/Messages.java
  src/main/java/tuteez/logic/commands/DeleteCommand.java
  src/main/java/tuteez/logic/parser/CliSyntax.java
  src/main/java/tuteez/logic/parser/DeleteCommandParser.java
  src/main/java/tuteez/model/AddressBook.java
  src/main/java/tuteez/model/Model.java
  src/main/java/tuteez/model/ModelManager.java
  src/test/java/tuteez/logic/commands/AddCommandTest.java
  src/test/java/tuteez/logic/commands/DeleteCommandTest.java
  src/test/java/tuteez/logic/parser/DeleteCommandParserTest.java
  src/test/java/tuteez/model/ModelManagerTest.java
Labels: priority.High

#71 Add `TelegramUsername` to a Student's contact details
  src/main/java/tuteez/logic/Messages.java
  src/main/java/tuteez/logic/commands/AddCommand.java
  src/main/java/tuteez/logic/commands/EditCommand.java
  src/main/java/tuteez/logic/parser/AddCommandParser.java
  src/main/java/tuteez/logic/parser/CliSyntax.java
  src/main/java/tuteez/logic/parser/EditCommandParser.java
  src/main/java/tuteez/logic/parser/ParserUtil.java
  src/main/java/tuteez/model/person/Person.java
  src/main/java/tuteez/model/person/TelegramUsername.java
  src/main/java/tuteez/model/util/SampleDataUtil.java
  src/main/java/tuteez/storage/JsonAdaptedPerson.java
  src/main/java/tuteez/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/tuteez/logic/LogicManagerTest.java
  src/test/java/tuteez/logic/commands/CommandTestUtil.java
  src/test/java/tuteez/logic/commands/EditPersonDescriptorTest.java
  src/test/java/tuteez/logic/parser/AddCommandParserTest.java
  src/test/java/tuteez/model/person/PersonTest.java
  src/test/java/tuteez/model/person/TelegramUsernameTest.java
  src/test/java/tuteez/storage/JsonAdaptedPersonTest.java
  src/test/java/tuteez/testutil/EditPersonDescriptorBuilder.java
  src/test/java/tuteez/testutil/PersonBuilder.java
  src/test/java/tuteez/testutil/PersonUtil.java
  src/test/java/tuteez/testutil/TypicalPersons.java
Labels: type.Enhancement, priority.High

#70 Add check for duplicate timing feature
  src/main/java/tuteez/logic/commands/AddCommand.java
  src/main/java/tuteez/logic/commands/CommandResult.java
  src/main/java/tuteez/logic/commands/EditCommand.java
  src/main/java/tuteez/model/person/lesson/Lesson.java
  src/main/java/tuteez/storage/JsonSerializableAddressBook.java
  src/test/java/tuteez/logic/commands/AddCommandTest.java
  src/test/java/tuteez/model/person/lesson/LessonTest.java
Labels: priority.High

#88 Fix issues with jar file built using Gradle
  build.gradle
  src/main/java/tuteez/model/util/SampleDataUtil.java
Labels: priority.High

#89 Up arrow goes to previous command
  src/main/java/tuteez/logic/commands/CommandHistory.java
  src/main/java/tuteez/ui/CommandBox.java
  src/main/java/tuteez/ui/MainWindow.java
  src/test/java/tuteez/logic/commands/CommandHistoryTest.java
Labels: priority.High

#85 Add `LessonManager` to `Addressbook` & reject clashing lessons
  src/main/java/tuteez/logic/commands/AddCommand.java
  src/main/java/tuteez/logic/commands/EditCommand.java
  src/main/java/tuteez/model/AddressBook.java
  src/main/java/tuteez/model/Model.java
  src/main/java/tuteez/model/ModelManager.java
  src/main/java/tuteez/model/ReadOnlyAddressBook.java
  src/main/java/tuteez/model/person/lesson/Day.java
  src/main/java/tuteez/model/person/lesson/Lesson.java
  src/main/java/tuteez/model/person/lesson/LessonManager.java
  src/main/java/tuteez/storage/JsonAdaptedLesson.java
  src/main/java/tuteez/storage/JsonSerializableAddressBook.java
  src/main/java/tuteez/ui/PersonCard.java
  src/test/java/tuteez/logic/commands/AddCommandTest.java
  src/test/java/tuteez/model/AddressBookTest.java
  src/test/java/tuteez/model/person/lesson/LessonManagerTest.java
  src/test/java/tuteez/model/person/lesson/LessonTest.java
  src/test/java/tuteez/testutil/PersonUtil.java
Labels: priority.High

#86 Add abbreviations for `delete` and `remark`
  src/main/java/tuteez/logic/commands/DeleteCommand.java
  src/main/java/tuteez/logic/commands/RemarkCommand.java
  src/main/java/tuteez/logic/parser/AddressBookParser.java
  src/test/java/tuteez/logic/parser/AddressBookParserTest.java
Labels: type.Enhancement, priority.High

#91 Fix remark json bug
  src/main/java/tuteez/model/remark/Remark.java
  src/main/java/tuteez/storage/JsonAdaptedPerson.java
  src/main/java/tuteez/storage/JsonAdaptedRemarkList.java
  src/test/java/tuteez/storage/JsonAdaptedPersonTest.java
Labels: type.Bug, priority.High

#92 Update Email and Address command fields to be optional when adding contacts
  src/main/java/tuteez/logic/Messages.java
  src/main/java/tuteez/logic/commands/AddCommand.java
  src/main/java/tuteez/logic/parser/AddCommandParser.java
  src/main/java/tuteez/logic/parser/EditCommandParser.java
  src/main/java/tuteez/logic/parser/ParserUtil.java
  src/main/java/tuteez/model/person/Address.java
  src/main/java/tuteez/model/person/Email.java
  src/main/java/tuteez/model/person/TelegramUsername.java
  src/main/java/tuteez/storage/JsonAdaptedPerson.java
  src/main/java/tuteez/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/tuteez/logic/commands/CommandTestUtil.java
  src/test/java/tuteez/logic/parser/AddCommandParserTest.java
  src/test/java/tuteez/logic/parser/EditCommandParserTest.java
  src/test/java/tuteez/logic/parser/ParserUtilTest.java
  src/test/java/tuteez/model/person/AddressTest.java
  src/test/java/tuteez/model/person/EmailTest.java
  src/test/java/tuteez/storage/JsonAdaptedPersonTest.java
Labels: type.Enhancement, priority.High

#94 Enable assertions in `build.gradle`
  build.gradle
Labels: type.Task, priority.High

#96 Add Null Check Assertions
  src/main/java/tuteez/logic/commands/AddCommand.java
  src/main/java/tuteez/model/person/lesson/Lesson.java
  src/main/java/tuteez/model/person/lesson/LessonManager.java
Labels: priority.High, severity.Low

#101 Add logger to the CommandHistory class
  src/main/java/tuteez/logic/commands/CommandHistory.java
Labels: priority.High, severity.Low

#111 Add logging for `AddRemarkCommand` and `DeleteRemarkCommand`
  src/main/java/tuteez/logic/commands/AddRemarkCommand.java
  src/main/java/tuteez/logic/commands/DeleteRemarkCommand.java
Labels: priority.Medium, severity.Low

#103 Update `AddCommand` and `EditCommand` usage error messages
  src/main/java/tuteez/logic/commands/AddCommand.java
  src/main/java/tuteez/logic/commands/EditCommand.java
Labels: type.Bug

#106 Update DG for `LessonManager`
  README.md
  docs/DeveloperGuide.md
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/LessonClassDiagram.puml
Labels: priority.Medium, type.Documentation

#100 Add log statements to Add, Delete, Edit commands and `LessonManager`
  src/main/java/tuteez/logic/commands/AddCommand.java
  src/main/java/tuteez/logic/commands/DeleteCommand.java
  src/main/java/tuteez/logic/commands/EditCommand.java
  src/main/java/tuteez/model/person/Person.java
  src/main/java/tuteez/model/person/lesson/LessonManager.java
Labels: priority.Medium, severity.Low

#119 Update DG to include command box class
  docs/DeveloperGuide.md
  docs/diagrams/CommandBoxSequenceDiagram.puml
Labels: priority.Medium, severity.Low

#123 Fix display bug
  src/main/java/tuteez/logic/commands/EditCommand.java
  src/main/java/tuteez/ui/DisplayCard.java
  src/main/java/tuteez/ui/DisplayCardPanel.java
  src/test/java/tuteez/logic/commands/EditCommandTest.java
Labels: type.Bug, priority.High, severity.High

#143 Make remark commands update displayed person
  src/main/java/tuteez/logic/commands/AddRemarkCommand.java
  src/main/java/tuteez/logic/commands/DeleteRemarkCommand.java
  src/main/java/tuteez/model/ModelManager.java
  src/test/java/tuteez/logic/commands/AddRemarkCommandTest.java
  src/test/java/tuteez/logic/commands/DeleteRemarkCommandTest.java
Labels: type.Enhancement, type.Bug, priority.Medium, severity.Medium, alpha-bug

#167 Bug Fix: Add clashing lessons for the same student
  src/main/java/tuteez/logic/commands/AddCommand.java
  src/main/java/tuteez/model/person/lesson/Lesson.java
Labels: type.Bug, priority.High, severity.Medium

#162 Add method to retrieve a student's next lesson
  src/main/java/tuteez/logic/commands/AddCommand.java
  src/main/java/tuteez/logic/commands/EditCommand.java
  src/main/java/tuteez/logic/parser/AddCommandParser.java
  src/main/java/tuteez/logic/parser/EditCommandParser.java
  src/main/java/tuteez/logic/parser/ParserUtil.java
  src/main/java/tuteez/model/person/Person.java
  src/main/java/tuteez/model/person/lesson/Day.java
  src/main/java/tuteez/model/person/lesson/Lesson.java
  src/main/java/tuteez/model/util/SampleDataUtil.java
  src/main/java/tuteez/storage/JsonAdaptedPerson.java
  src/test/java/tuteez/logic/parser/ParserUtilTest.java
  src/test/java/tuteez/model/person/PersonTest.java
  src/test/java/tuteez/model/person/lesson/LessonTest.java
  src/test/java/tuteez/testutil/EditPersonDescriptorBuilder.java
  src/test/java/tuteez/testutil/PersonBuilder.java
  src/test/java/tuteez/testutil/PersonUtil.java
Labels: type.Enhancement, priority.Medium

#131 Make error messages more specific for `remark` command
  src/main/java/tuteez/logic/Messages.java
  src/main/java/tuteez/logic/parser/ParserUtil.java
  src/main/java/tuteez/logic/parser/RemarkCommandParser.java
  src/test/java/tuteez/logic/parser/ParserUtilTest.java
  src/test/java/tuteez/logic/parser/RemarkCommandParserTest.java
Labels: type.Bug, priority.Medium, severity.Medium

#168 Relocate hashmap
  src/main/java/tuteez/model/person/lesson/Day.java
  src/main/java/tuteez/model/person/lesson/Lesson.java
  src/test/java/tuteez/model/person/lesson/DayTest.java
  src/test/java/tuteez/model/person/lesson/LessonTest.java
Labels: type.Enhancement, severity.VeryLow
